### ISSUE TITLE
Need to add dependency for LWP::Protocol::https

### ISSUE THREAD

**Issue by whosgonna** [whosgonna/Zabbix-Tiny.pm#13]
After installing Zabbix::Tiny on a host today (and trying to connect to a zabbix server that was using https), the following error was received:
`Protocol scheme 'https' is not supported (LWP::Protocol::https not installed) at /usr/local/lib/perl5/site_perl/Zabbix/Tiny.pm line 63.`

The quick solution is (simply) to install LWP::Protocol::https, however this should be added as a dependency into the cpan distro.

**Comment by richlv** [comment]
"After installing LWP::Protocol::https..." - this seems to reference the same module everywhere. was that intended ?

**Comment by whosgonna** [comment]
It looks like it is not installed along with Zabbix::Tiny when installing from CPAN.  Likely I didn't list it as a dependency.

**Comment by richlv** [comment]
ok, so the first instance of "LWP::Protocol::https" should probably read "Zabbix::Tiny" :)

**Comment by whosgonna** [comment]
Yes. Corrected.
