### ISSUE TITLE
empty response from the API not handled properly

### ISSUE THREAD

**Issue by richlv** [whosgonna/Zabbix-Tiny.pm#17]
in some cases zabbix api returns a completely empty string, not even a json object. zabbix::tiny doesn't handle that properly :

malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/lib/perl5/site_perl/5.18.2/Zabbix/Tiny.pm line 136.

line 136 is :

`$self->{last_response} = decode_json( $self->{post_response}->{_content} );`
if i `print Dumper($self->{post_response}->{_content});` before that, it is empty :
`$VAR1 = '';`

in this specific case, zabbix api run out of memory when handling an event.get method request

**Comment by whosgonna** [comment]
What would be the preferred behavior?  Right now it should `die()` by design.  It should be possible to add some exception handling, but what would you like to see it do instead?

**Comment by richlv** [comment]
human-friendly error message should suffice - something like "Empty response received from the Zabbix API. This can indicate an error on the API side like running out of memory."

**Comment by whosgonna** [comment]
How much can you reproduce this?  For comparison do you know how the python library, etc. would handle this?  If handling this as a bash script using calls to curl to pass data, what would occur?

It might be good to `or carp`... off of line 136.

If this is currently a common problem for you,  you might want to look at Try::Tiny for exception handling in your script.

**Comment by richlv** [comment]
i can reproduce it at will by doing an unfiltered event.get ;)
it's not a problem for me now that i know what causes it, but the error message is quite ugly.
in my naive approach, i'd just check the returned value for being an empty string and output a user friendly error message, although erroring out with a better message if it's non-empty non-json might be useful, too
