### ISSUE TITLE
Please add support for Zabbix 6.4

### ISSUE THREAD

**Issue by odmdas** [whosgonna/Zabbix-Tiny.pm#31]
Please add support for Zabbix 6.4

In Zabbix 5.4 [changes][0]:
* user.login: Renamed parameter `user` → `username`.

This parameter was [removed][1] in Zabbix 6.4 : 
* user.login: Removed support for deprecated parameter `user`.

Other changes in Zabbix 6.4:
* Authorization method changed from `auth` parameter to `Authorization` header.
* Deprecated parameter auth.

Zabbix 4.0 LTS and 5.0 LTS are still [supported][2], so compatibility with them
should also be preserved.

[0]: https://www.zabbix.com/documentation/5.4/en/manual/api/changes_5.2_-_5.4#user
[1]: https://www.zabbix.com/documentation/6.4/en/manual/api/changes#user
[2]: https://www.zabbix.com/life_cycle_and_release_policy

**Comment by whosgonna** [comment]
A few notes:

1. I don't admin a Zabbix server anymore.  I'm happy to work on this change, but I don't have a current host to test against.  Do you have a link to the  most simplified docker/docker-compose for zabbix? I'm sure I _could_ build it up from scratch, but that will delay an such resolution.

1. Can you link to the auth method change for 6.4? (from `auth` to `Authorization:` header)

1. There's going to be a required interface change within `Zabbix::Tiny` to support this.  My current thought is that the argument passed to the constructor will directy translates what gets passed to the Zabbix API. This would keep any changes from breaking existing scripts, and not force a new parameter like `version` to the constructor.  Anyone upgrading Zabbix to a version that doesn't suport `auth`  would also need to make a minor upgrade to their scripts using `Zabbix::Tiny`, but from my POV, that's a change forced by Zabbix, not me.

**Comment by odmdas** [comment]
Hi,
1. There are multiple official [images][0]
2. [Authorization methods][1] for 6.4
3. You may also take into account the possibility of requesting Zabbix API version to decide on the parameters used, as is done in a similar [module][3]  for Python. The `apiinfo.version` method does not require authentication.

[0]: https://www.zabbix.com/container_images
[1]: https://www.zabbix.com/documentation/6.4/en/manual/api#authorization-methods
[3]: https://github.com/lukecyca/pyzabbix/blob/master/pyzabbix/api.py

**Comment by ISiroshtan** [comment]
@whosgonna would you kindly review proposed [PR](https://github.com/whosgonna/Zabbix-Tiny.pm/pull/32) for support of Zabbix 6.4. 

Also, it does not cover changes in Authorization method as old one still supported by Zabbix 6.4. It will possibly be removed with release of Zabbix 7.0, then more changes would be required.

**Comment by richlv** [comment]
We're working on an upgrade to Zabbix 6.4 and hit the issue with user->username.
@whosgonna, does the PR above look reasonable?

**Comment by whosgonna** [comment]
Hi,

I hadn't seen the PR - my bad.  I just looked at it, and there's a few minor personal opinions that I have. With that in mind, I also don't really have time to curate it to the ideal level.  I provided feedback to @ISiroshtan , and if he's willing to make the changes I suggest, that would be awesome.  If not, I'm willing to merge his changes "as-is" so that a working version is shipped.  Is it good to wait up to a week for his feedback?  I'll then need a little time to do the stuff to push it to CPAN, but that shouldn't take too long.

**Comment by ISiroshtan** [comment]
I will give a look on a weekend and will try fix all the comments by Monday.

**Comment by richlv** [comment]
Hi @ISiroshtan, noticed your recent updates - any still pending, or is this good for Ben's review?

**Comment by ISiroshtan** [comment]
Hi @richlv, I adressed most of the points rised as part of review to the best of my knowledge. I think the single note I did not address is:
> It might also benefit from a default value.

As I fail to understand benefit of it, if we will get version from server every time (unless user explicitly provides it). Once again, tested auth and some basic API requests against legacy 4.4 and new 6.4 both with providing version explicitly and witout.

**Comment by whosgonna** [comment]
I should be able to get this merged and pushed to CPAN this week

**Comment by richlv** [comment]
Heya @whosgonna, sorry to bother you - just wanted to check whether you had some time for this :)

**Comment by whosgonna** [comment]
Sorry for the delay.  I'm merging now, and will re-acquaint myself with the process for updating to CPAN and hopefully get it there this morning.

**Comment by whosgonna** [comment]
> It might also benefit from a default value.

This comment was made during a "top down" reading of the code changes, before I saw that the module "automagically" gets the version from the Zabbix server prior to login so there is no need for a default value.

**Comment by whosgonna** [comment]
Note:  Some tests failing.  These might be related to the code changes, *however*  I'll need to update the tests prior to release.  Working it now.

**Comment by whosgonna** [comment]
Module design is that the `Zabbix::Tiny` object can be instantiated without having to connect to a zabbix server.  This enables testing of code using the Zabbix module, as well as the ability to define the object early on, but abort code without having to ever have created a connection.

The new code retrieves the `version` attribute during the `BUILD` phase which then _requires_ a connection.  I'm working to change the `version` attribute from `ro` to `lazy`, which will not populate until the attribute is requested.

**Comment by whosgonna** [comment]
After changing the attribute type to lazy, and changing the `version_get` sub to `_build_version` (as this is how `lazy` prefers the subroutine to be named), tests were still failing.  This turned out to be because Test::LWP::UserAgent` requires that the requests and responses be pre-defined (which makes sense), so I needed to add a response for `apiiinfo.version` to the tests.  It's working now, but as a future todo, it would probably be better to refactor out the `map_response`s to a small helper library in the test directory.

**Comment by richlv** [comment]
Yay, thank you so much :)
It is merged now, but CPAN release pending, right?

**Comment by whosgonna** [comment]
By this time it should already be available. Note that it looks like I left a module I was using in the test plan, so I'll need to make a fix for that, but it won't change any functionality

**Comment by whosgonna** [comment]
Version 2.0.1 was just pushed.  It's a change in version formatting, so fingers crossed that it doesn't compound things....

**Comment by richlv** [comment]
Yay, it's available and works with Zabbix 6.4 :)
Thank you so much Ben, Ihor,

**Comment by whosgonna** [comment]
I believe 2.0.1 should e the current version, that has the fixed tests.

**Comment by richlv** [comment]
Yes, to clarify, 2.0.1 was available in CPAN.
